# SITE CONFIGURATION
title: Mappia Documentation
author: CSR
description: > # Meta description of Homepage
  A service to share maps. Publish maps online, and easily create customized platforms
  using geographic data.

# SEO PLUGIN
social:
  name: CSR
  links:
    - http://maps.csr.ufmg.br

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Documentation', link: '/documentation'}
  - {name: 'API Reference', link: '/api'}
  - {name: 'Publish your Maps', link: '/mappia_publisher'}
  - {name: 'About', link: '/about'}

tagline: >
  Documentation for using Mappia

hero_img: posts/CSR-Maps-bg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: null # email for form submission

twitter_username: null
github_username: CSRMaps
instagram_username: null

disqus:
  shortname: null # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

collections:
  examples:
    output: true
  elements:
    output: true
  raw_maps:
    output: true

future: true
timezone: America/Sao_Paulo

compress_html:
  clippings: all

maps:
  base: https://maps.csr.ufmg.br/?
  calculator: https://maps.csr.ufmg.br/calculator/?
  editor: https://maps.csr.ufmg.br/editor/?

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
